recipe:
  shape:
    - "CRC"
    - "CHC"
    - " C "
  translations:
    c: minecraft:copper_ingot
    r: minecraft:comparator
    h: minecraft:hopper

item:
  name: "Sorting Hopper"
  lore: ""
  custom-model-data: -1
